"""initial_schema

Revision ID: 598193a64046
Revises:
Create Date: 2026-09-27 20:13:03.600438

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "598193a64046"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_runs",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("claim_id", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=50), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("output_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_runs_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_runs_idempotency_key"), ["idempotency_key"], unique=True
        )

    op.create_table(
        "extraction_snapshots",
        sa.Column("claim_id", sa.String(length=100), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    with op.batch_alter_table("extraction_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extraction_snapshots_snapshot_hash"), ["snapshot_hash"], unique=False
        )

    op.create_table(
        "stored_documents",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("claim_id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("internal_path", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stored_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stored_documents_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stored_documents_sha256"), ["sha256"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stored_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_stored_documents_claim_id"))

    op.drop_table("stored_documents")
    with op.batch_alter_table("extraction_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_snapshots_snapshot_hash"))

    op.drop_table("extraction_snapshots")
    with op.batch_alter_table("audit_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_runs_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_audit_runs_claim_id"))

    op.drop_table("audit_runs")
    op.drop_table("claims")
    # ### end Alembic commands ###
